name: Auto Merge

on:
  pull_request:
    types: [labeled, review_requested, submitted]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
